### PR TITLE
Users UI added inside Dashboard

### PR DESCRIPTION
**Pull request by codebloded**
Users UI added inside the dashboard
Screenshot (17)

Screenshot (18)

### CODE REVIEW

**Comment by lakshya-20** [comment]
Change "Edit Event to Edit User's Detail" on top of the modal.

**Comment by codebloded** [comment]
oops soory ,but its  already done , that screen shot is captured earlier😅

**Comment by ravisaxena23** [comment]
@codebloded please add new ss

**Comment by codebloded** [comment]
Screenshot (20)

**Comment by codebloded** [comment]
@ravisaxena23  DONE 👍

**Review by lakshya-20 — APPROVED** [review]

**Pull request merged**
