### PR TITLE
Fixed Light-Dark Mode, Added Prettier Config

### PR DESCRIPTION
**Pull request by NiketanG**
- :bug:  Added ThemeContext for easier access and toggling of theme. Uses React Context so that theme works on all pages #250 
- :art:  Added Prettier config, and updated Eslint to work with Prettier

### CODE REVIEW

**Comment by Ritwik880** [comment]
Hii @NiketanG, can you please share some screenshot shots of changes you have done.

**Comment by NiketanG** [comment]
> Hii @NiketanG, can you please share some screenshot shots of changes you have done.

Sure ! 
Screenshot from 2020-10-02 13-15-59
Screenshot from 2020-10-02 13-15-54
Screenshot from 2020-10-02 13-15-44

**Comment by Ritwik880** [comment]
It looks nice @NiketanG, but it will be more attractive if you will do the same for background:
Screenshot from 2020-10-02 13-35-40

**Comment by NiketanG** [comment]
> It looks nice @NiketanG, but it will be more attractive if you will do the same for background:
> Screenshot from 2020-10-02 13-35-40

Sure, will do !

**Comment by NiketanG** [comment]
@Ritwik880 Do you have a Dark Variant of the background Image ?

**Comment by Ritwik880** [comment]
> @Ritwik880 Do you have a Dark Variant of the background Image ?

No

**Comment by Isha2103** [comment]
@NiketanG Background is not suiting with text. Please fix this.

**Comment by NiketanG** [comment]
@Isha2103 @Ritwik880 I've updated the PR with new Fixes. Take a look:
Screenshot from 2020-10-02 14-54-36
Screenshot from 2020-10-02 14-54-21

**Review by Isha2103 — APPROVED** [review]
Nice :)

**Comment by Ritwik880** [comment]
@NiketanG  Looks great

**Review by Ritwik880 — APPROVED** [review]

**Comment by ravisaxena23** [comment]
Thank you for hard work @Ritwik880

**Comment by ravisaxena23** [comment]
thanks you @NiketanG

**Pull request merged**
