### PR TITLE
251 enhance live event

### PR DESCRIPTION
**Pull request by KaylaKremer**
https://github.com/technojam/technojam-frontend/issues/251

### CODE REVIEW

**Comment by lakshya-20** [comment]
While closing it is increasing its height which does not look good.

**Comment by KaylaKremer** [comment]
@lakshya-20 

Sure, I can fix that!

**Comment by KaylaKremer** [comment]
@lakshya-20 

Ok, should be fixed now! I also went ahead and fixed the issue of the loader displaying at the same time as the text and center-aligned it.

**Comment by lakshya-20** [comment]
Hey @KaylaKremer 
The previous bug is solved but now it is going out of the width of the screen
image

**Comment by ravisaxena23** [comment]
@KaylaKremer are you working on it?

**Comment by KaylaKremer** [comment]
@ravisaxena23 Yes I am

**Comment by KaylaKremer** [comment]
@Ritwik880 

Desktop:
Screen Shot 2020-10-02 at 1 12 15 PM
Screen Shot 2020-10-02 at 1 12 23 PM

Mobile:
Screen Shot 2020-10-02 at 1 12 37 PM
Screen Shot 2020-10-02 at 1 12 43 PM

**Review by mohdorusaid — APPROVED** [review]

**Review by Ritwik880 — APPROVED** [review]

**Review by Ritwik880 — APPROVED** [review]

**Review by lakshya-20 — APPROVED** [review]

**Comment by lakshya-20** [comment]
@KaylaKremer Thanks for your hard work! :)

**Pull request merged**
