### PR TITLE
Redesigned form for creating events on dashboard

### PR DESCRIPTION
**Pull request by alexandramj92**

### CODE REVIEW

**Comment by lakshya-20** [comment]
Hey @alexandramj92 can you please elaborate little what have you done? :)

**Comment by alexandramj92** [comment]
> Hey @alexandramj92 can you please elaborate little what have you done? :)

Yes no problem! So I redesigned the form to make it look nicer and more user friendly.
- separated out the fields into separate components and by category 
- added a stepper so that the user only sees one category at a time
- added validation to ensure that all the required fields are completed before submitting the form
- added a success page once submitted that also allows the user to be redirected to the start of the form if they would like to add another event
- made sure that it is mobile responsive

I included screenshots of what I did. 

addeventone
mobileresponsive
addeventfour
addeventthree
addeventtwo

**Comment by ravisaxena23** [comment]
thank you @alexandramj92

**Comment by alexandramj92** [comment]
> thank you @alexandramj92

Hi @ravisaxena23 ! I was wondering if you can approve this pull request since you merged it? I think it needs to be approved in order to count for hacktoberfest.

**Comment by ravisaxena23** [comment]
If pr is merged I think it is already approved.

**Pull request merged**
