### PR TITLE
:bug: Fixed name color not changing on dark mode and changed social icons color

### PR DESCRIPTION
**Pull request by abdulsamad**
TechnoJam (1)
TechnoJam

Switched to the functional component, added prop types, and fixed the bug.
It may have issues (probably :sweat_smile: ) as this is my first contribution.

### CODE REVIEW

**Comment by Ritwik880** [comment]
@abdulsamad I don't think the issue has resolved yet. Please have a  look into it.

Screenshot from 2020-10-15 19-53-12

**Comment by abdulsamad** [comment]
Should I also change mail icon color?

**Comment by abdulsamad** [comment]
Peek 2020-10-15 20-09

@Ritwik880 It's working on my machine locally and I can see the code in the pull request.

bug

**Comment by abdulsamad** [comment]
Maybe I've messed up in sending a pull request. Can you please check?

**Review by Ritwik880 — APPROVED** [review]

**Review by cryolune — APPROVED** [review]

**Comment by abdulsamad** [comment]
Sorry accidentally clicked on close pull request 😅

**Review by cryolune — APPROVED** [review]

**Comment by mohdorusaid** [comment]
Hey @abdulsamad , we don't want to change the class-based component to a functional one, and one more PR has done this work without resorting to these changes.
However, we value your efforts and we won't close this PR. The hacktoberfest label has already been added, so this PR will be counted in your contributions.
Happy hacking!

**Comment by abdulsamad** [comment]
@mohdorusaid No problem

**Pull request closed without merging**
