### PR TITLE
dark mode contrast issue fix in teams inner page

### PR DESCRIPTION
**Pull request by itsvvishnu**
Text color contrast issue in team's inner page when toggling to dark mode has been fixed in this pr

### CODE REVIEW

**Comment by Ritwik880** [comment]
Hii @itsvvishnu  can you please share some screen shots of the changes you have made.

**Comment by itsvvishnu** [comment]
> Hii @itsvvishnu can you please share some screen shots of the changes you have made.

code or webpage?

**Comment by Ritwik880** [comment]
webpage

**Comment by itsvvishnu** [comment]
> webpage

Screenshot from 2020-10-18 22-49-20
Team member's name was not readable in darkmode before

**Comment by Ritwik880** [comment]
@itsvvishnu Please have a look into #277 Pr.

**Comment by itsvvishnu** [comment]
> @itsvvishnu Please have a look into #277 Pr.

The issue was not closed that's why i made a pr, and I did not change the class based component into a functional component, i kept everything the same

**Review by mohdorusaid — APPROVED** [review]

**Review by Ritwik880 — APPROVED** [review]

**Review by theakhiljha — APPROVED** [review]

**Pull request merged**
